### ISSUE TITLE
SUMMARY

### ISSUE THREAD

**Issue by ad3429** [rayeusi/dasmoto#5]
**Summary Grade: Satisfactory**

Good job! Your files are organized nicely, and you did a great job of following the client specification -- this is an important skill to have as a developer and you seem to understand that. Moreover, you generally followed excellent code practice, so make sure to keep that up!

I have made some comments in your code to take note of. First off, great job making use of id's and classes appropriately -- many learners seem to confuse this concept, so great job getting that right. You also did a great job making sure to comment your HTML, which is something learners often forget to do. You should also make sure to do the same for your stylings in your CSS file. This greatly helps your development flow, especially as your projects get larger and more complex since they serve as a reminder to why you decided to code something a particular way. Here is a quick refresher on commenting in CSS:

<img width="178" alt="css comment" src="https://user-images.githubusercontent.com/25671399/36079818-4f2f0dd0-0f55-11e8-9f35-ec13015d1b54.png">

Moreover, nice job making sure to format/indent your HTML properly. 

Great job overall! As a further challenge, try using css to design your webpage even further! You did a great job in following the client specification, but for your own practice you should see how creative you can get by taking the design/styling of your site to the next level (for example, you can try experimenting with background colors on your other divs).

**Comment by rayeusi** [comment]
Thank you for your comments, @ad3429 These are all very helpful, especially having to put comments on the CSS file to improve my development flow. I'm excited to learn more and continue to improve! Appreciate your help!
